# Generated by Django 4.2.9 on 2024-03-10 10:46

from django.db import migrations, models
import myapp.models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_insight_added_alter_insight_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='intensity',
            field=models.IntegerField(blank=True, null=True, validators=[myapp.models.validate_optional_integer]),
        ),
    ]
