# Generated by Django 4.2.9 on 2024-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_insight_intensity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'verbose_name_plural': 'Insights'},
        ),
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='insight',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
