# Generated by Django 4.2.9 on 2024-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_insight_options_alter_insight_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=models.CharField(max_length=100),
        ),
    ]
