# Generated by Django 4.2.9 on 2024-03-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_insight_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=models.CharField(max_length=100),
        ),
    ]
