# Generated by Django 4.2.9 on 2024-03-11 18:58

from django.db import migrations
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_insight_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='added',
            field=myapp.models.CustomDateTimeField(),
        ),
        migrations.AlterField(
            model_name='insight',
            name='published',
            field=myapp.models.CustomDateTimeField(),
        ),
    ]
